package presentacion.form;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PopUp_Estadistica extends JDialog {
    public JPanel panel1;
    private JLabel lab;
    private JButton cerrarButton;

    public PopUp_Estadistica(String s) {
        super();
        setModal(false);
        setResizable(false);
        $$$setupUI$$$();
        lab.setText(s);

        cerrarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                dispose();
            }
        });
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, -1));
        panel1.setBackground(new Color(-14013910));
        panel1.setEnabled(false);
        panel1.setPreferredSize(new Dimension(500, 200));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        cerrarButton = new JButton();
        cerrarButton.setBackground(new Color(-12961222));
        cerrarButton.setBorderPainted(false);
        cerrarButton.setFocusPainted(false);
        cerrarButton.setForeground(new Color(-1));
        cerrarButton.setText("Cerrar");
        panel1.add(cerrarButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(10, 20), null, 0, false));
        lab = new JLabel();
        lab.setBackground(new Color(-14013910));
        lab.setForeground(new Color(-1));
        lab.setText("Label");
        panel1.add(lab, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
